apiVersion: v1
kind: Secret
metadata:
  name: mlflow-postgres-secret
  namespace: bestshot-platform
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: mlflowdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-postgres-pvc
  namespace: bestshot-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bestshot-platform
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: mlflow-postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: mlflow-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: bestshot-platform
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
