apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: bestshot-platform
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostAliases:
      - ip: "129.114.97.101"
        hostnames:
        - chi.tacc.chameleoncloud.org
      containers:
      - name: mlflow
        image: ghcr.io/anokhimehta/bestshot-mlflow:latest
        command:
          - /bin/sh
          - -c
          - >
            mlflow server
            --backend-store-uri postgresql://user:password@postgres/mlflowdb
            --artifacts-destination s3://proj19-mlflow-artifacts/
            --serve-artifacts
            --host 0.0.0.0
            --allowed-hosts "*"
            --cors-allowed-origins "*"
            --port 5000
            --uvicorn-opts "--workers 1 --timeout-keep-alive 300"
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: https://chi.tacc.chameleoncloud.org:7480
        envFrom:
        - secretRef:
            name: mlflow-artifact-credentials
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "8Gi"