global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # scrape the BestShot FastAPI server
  - job_name: "bestshot"
    static_configs:
      - targets: ["10.52.2.226:8000"] # host network, so localhost works
    metrics_path: "/metrics"
