#run to make sure everything working in chameleon environment
experiment_name: chameleon-test
data_dir: /data/koniq10k
batch_size: 32
epochs: 1
lr: 0.0001
limit: 200 #for testing, we only use a small subset of the data
num_workers: 0
