FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install fastapi uvicorn torch torchvision onnxruntime pillow numpy

COPY app.py model.py schemas.py ./
COPY models/ ./models/

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]